# Generated by Django 2.1.1 on 2018-10-17 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_author', models.CharField(max_length=50)),
                ('news_date', models.DateField(default=django.utils.timezone.now)),
                ('news_content', models.TextField()),
            ],
        ),
    ]
