# Generated by Django 2.1.1 on 2018-10-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
    ]
