# Generated by Django 2.1.1 on 2018-12-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20181215_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='user',
            new_name='about_user',
        ),
    ]
