# Generated by Django 2.1.1 on 2018-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20181215_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_user',
        ),
        migrations.AddField(
            model_name='about',
            name='author',
            field=models.TextField(default='Anonymous'),
            preserve_default=False,
        ),
    ]
